import { defineConfig } from 'oxlint';

export default defineConfig({
  plugins: ['typescript', 'react', 'jsx-a11y'],

  jsPlugins: ['eslint-plugin-perfectionist'],

  categories: {
    correctness: 'off',
  },

  options: {
    typeAware: true,
    typeCheck: true,
    maxWarnings: 10,
  },

  env: {
    builtin: true,
    browser: true,
  },

  ignorePatterns: [
    'dist',
    'build',
    'coverage',
    'node_modules',
    'package-lock.json',
    'yarn.lock',
    'bun.lock',
    '**/*/vite-env.d.ts',
  ],

  overrides: [
    {
      files: ['**/*.{ts,tsx}'],

      rules: {
        'perfectionist/sort-jsx-props': [
          'error',
          {
            type: 'line-length',
            order: 'asc',
            ignoreCase: true,
            groups: [
              'important',
              'shorthand-prop',
              'unknown',
              'multiline-prop',
              'callback',
            ],
            customGroups: [
              {
                groupName: 'important',
                elementNamePattern: '^(id|key|ref)$',
              },
              {
                groupName: 'callback',
                elementNamePattern: '^on.+',
              },
            ],
          },
        ],

        'constructor-super': 'error',
        'for-direction': 'error',
        'getter-return': 'error',
        'no-async-promise-executor': 'error',
        'no-case-declarations': 'error',
        'no-class-assign': 'error',
        'no-compare-neg-zero': 'error',
        'no-cond-assign': 'error',
        'no-const-assign': 'error',
        'no-constant-binary-expression': 'error',
        'no-constant-condition': 'error',
        'no-control-regex': 'error',
        'no-debugger': 'error',
        'no-delete-var': 'error',
        'no-dupe-class-members': 'error',
        'no-dupe-else-if': 'error',
        'no-dupe-keys': 'error',
        'no-duplicate-case': 'error',
        'no-empty': 'error',
        'no-empty-character-class': 'error',
        'no-empty-pattern': 'error',
        'no-empty-static-block': 'error',
        'no-ex-assign': 'error',
        'no-extra-boolean-cast': 'error',
        'no-fallthrough': 'error',
        'no-func-assign': 'error',
        'no-global-assign': 'error',
        'no-import-assign': 'error',
        'no-invalid-regexp': 'error',
        'no-irregular-whitespace': 'error',
        'no-loss-of-precision': 'error',
        'no-misleading-character-class': 'error',
        'no-new-native-nonconstructor': 'error',
        'no-nonoctal-decimal-escape': 'error',
        'no-obj-calls': 'error',
        'no-prototype-builtins': 'error',
        'no-redeclare': 'error',
        'no-regex-spaces': 'error',
        'no-self-assign': 'error',
        'no-setter-return': 'error',
        'no-shadow-restricted-names': 'error',
        'no-sparse-arrays': 'error',
        'no-this-before-super': 'error',
        'no-undef': 'error',
        'no-unexpected-multiline': 'error',
        'no-unreachable': 'error',
        'no-unsafe-finally': 'error',
        'no-unsafe-negation': 'error',
        'no-unsafe-optional-chaining': 'error',
        'no-unused-labels': 'error',
        'no-unused-private-class-members': 'error',
        'no-unused-vars': 'warn',
        'no-useless-backreference': 'error',
        'no-useless-catch': 'error',
        'no-useless-escape': 'error',
        'no-with': 'error',
        'require-yield': 'error',
        'use-isnan': 'error',
        'valid-typeof': 'error',
        'no-array-constructor': 'error',
        'no-unused-expressions': 'error',
        'typescript/ban-ts-comment': 'error',
        'typescript/no-duplicate-enum-values': 'error',
        'typescript/no-empty-object-type': 'error',
        'typescript/no-explicit-any': 'warn',
        'typescript/no-extra-non-null-assertion': 'error',
        'typescript/no-misused-new': 'error',
        'typescript/no-namespace': 'error',
        'typescript/no-non-null-asserted-optional-chain': 'error',
        'typescript/no-require-imports': 'error',
        'typescript/no-this-alias': 'error',
        'typescript/no-unnecessary-type-constraint': 'error',
        'typescript/no-unsafe-declaration-merging': 'error',
        'typescript/no-unsafe-function-type': 'error',
        'typescript/no-wrapper-object-types': 'error',
        'typescript/prefer-as-const': 'error',
        'typescript/prefer-namespace-keyword': 'error',
        'typescript/triple-slash-reference': 'error',
        'import/named': 'off',
        'import/namespace': 'error',
        'import/default': 'error',
        'import/export': 'error',
        'import/no-named-as-default': 'warn',
        'import/no-named-as-default-member': 'warn',
        'import/no-duplicates': 'warn',
        'react/display-name': 'error',
        'react/jsx-key': 'error',
        'react/jsx-no-comment-textnodes': 'error',
        'react/jsx-no-duplicate-props': 'error',
        'react/jsx-no-target-blank': 'error',
        'react/jsx-no-undef': 'error',
        'react/no-children-prop': 'error',
        'react/no-danger-with-children': 'error',
        'react/no-direct-mutation-state': 'error',
        'react/no-find-dom-node': 'error',
        'react/no-is-mounted': 'error',
        'react/no-render-return-value': 'error',
        'react/no-string-refs': 'error',
        'react/no-unescaped-entities': 'error',
        'react/no-unknown-property': 'error',
        'react/no-unsafe': 'off',
        'react/react-in-jsx-scope': 'off',
        'react/require-render-return': 'error',
        'object-shorthand': [
          'error',
          'always',
          {
            avoidQuotes: true,
          },
        ],
        'jsx-a11y/media-has-caption': 'off',
        'react/rules-of-hooks': 'error',
        'react/exhaustive-deps': 'warn',
        'react/only-export-components': [
          'warn',
          {
            allowConstantExport: true,
          },
        ],
        'typescript/no-non-null-assertion': 'off',
        'typescript/no-empty-interface': 'warn',
        'typescript/explicit-function-return-type': [
          'off',
          {
            allowExpressions: true,
            allowTypedFunctionExpressions: true,
            allowHigherOrderFunctions: true,
          },
        ],
      },
    },
  ],
});
